### PR TITLE
fix issue #65

### PR DESCRIPTION
**Pull request by Abdelaziz18003**
this commit will not fix the issue alone. you have to edit firebase rules in firebase console like that :

```
"posts": {
      "$id": {
        "author": {
          ".validate": "newData.isString()"
        },
        "body": {
          ".validate": "newData.isString()"
        },
        **************************************
        ****delete the rule below ($tags)****
        **************************************
        "tags": { 
          ".validate": "newData.hasChildren()"
        },
        "title": {
          ".validate": "newData.isString()"
        },
        "img": {
          ".validate": "newData.isString()"
        },
        "created": {
          // ".validate": "newData.val() < now"
        },
        **************************************
        ****delete the rule below ($other)**** 
        **************************************
        "$other": { 
          ".validate": false
        }
```

like this the issue normally should be fixed

### CODE REVIEW

**Comment by mahnouman** [comment]
Hello,
I am trying to understand the code, why tags: [], changed to tags: '' ?
I assume tags are a set of values, for example if tags in post are: programming, javascript, computers. This means the post have three tags not a single tag.
I am trying to avoid commits which fixes an issue but possibly creates another one.

**Comment by mahnouman** [comment]
Hello Just noticed a split function, so do the tag values stored separately in the db after the string being split or we store the raw combined string? Thanks

**Comment by Abdelaziz18003** [comment]
I didn't change the logic in this fix at all. Yes, the tags are stored separately in the db after spliting the string.

**Comment by mahnouman** [comment]
Thanks Abdelaziz, will merge this then and see how it goes.

**Comment by Abdelaziz18003** [comment]
Ok .. but don't forget to update the database rules on firebase in order to fix the issue of adding posts without tags .. this pull request fix the frontend side of the issue .. the other side is concerning rules that are preventing adding a post without tags.

**Comment by mahnouman** [comment]
yes no worries, I got that. For new implementations it will be pushed with Firebase init, right?

**Pull request merged**
