### PR TITLE
routing from DB #138 (first part)

### PR DESCRIPTION
**Pull request by Abdelaziz18003**
This is the first part to solve this issue as I understand it. I will add other missing parts when we are OK for that part. To test it you have to enter the data manually to the database like shown in the image below containing the path and the name of the component inside templates folder. [(read this link to understand why we need a separate folder for dynamic templates )](http://quasar-framework.org/guide/app-lazy-loading---code-splitting.html). then enter the dynamic urls after the hash sign /#/dynamic-url . I switched temporary to vue-router hash mode just for testing and I will switch it back when everything is Ok.

capture1

### CODE REVIEW

**Comment by mahnouman** [comment]
Hello Abdelaziz,
Can I call template 1 with routex and routey, where each can display the sa,e tempalte but with different dataset?
Thanks

**Comment by Abdelaziz18003** [comment]
Ok so if I understand your question well. Yes we will be able to call the same template with different routes. for example (supposing we have the routes above in the image) we can do it like this:

- /dynamic1?content_id=1 to display the content 1 in the Template1.vue
- /dynamic2?content_id=1 to display the content 1 in the Template2.vue
- /dynamic2?content_id=15 to display the content 15 in the Template2.vue

The process of fetching the needed data and displaying it will be handled in the template. for example when the route "/dynamic1/content_id=5" is reached. The content 5 is fetched and displayed inside Template1.

**Comment by mahnouman** [comment]
Hello abdelaziz. I mean can we do this with two different routes not the same route with two different parameters after the question mark

**Comment by Abdelaziz18003** [comment]
Hi Mahmoud, yes we can do this by adding an other route to "templates" that point to the same template. for example:

```
{
  path: '/route1',
  component: 'Template1'
},
{
  path: '/route2',
  component: 'Template1'
}
```

now both `/route1` and `route2` point to `Template1`. Concerning data to render in the template we have to pass it's identifer for example `/route1/content1` or `/route1?content_id=1` we will get this identifier in the template then get the corresponding data and display it.

**Comment by mahnouman** [comment]
Do the data identifier needs to be part of the url? Cant the router pass it from the database to the tenplate? What i want to store in db ia a route using a template to display specific content. So the content identifier that we want to display is in the db.

**Comment by mahnouman** [comment]
Hello, I am merging then testing, since we need this in the code for the rest of upcoming pull requests.

**Pull request merged**
