### PR TITLE
first part of issues fixing

### PR DESCRIPTION
**Pull request by Abdelaziz18003**

### CODE REVIEW

**Comment by mahnouman** [comment]
Hello, one of the files is referencing an external library (Google fonts), for everything /admin/* it must not be dependent on an external source.

**Comment by mahnouman** [comment]
Seems this google font is in index.html in root. If this is something we fix for the app it should be /app/ something . Please explain why we need to add code to the root index.html and what are the alternatives for this, I would like to keep the root index as empty as possible so everything for app is inside /app and everything /admin is for the management console.

Please add inline code comments to explain the code, thank you

**Comment by Abdelaziz18003** [comment]
Hi, I removed external fonts from index.html

**Comment by mahnouman** [comment]
Thank you, merging.

**Pull request merged**
