### PR TITLE
add database hello world data (issue #103)

### PR DESCRIPTION
**Pull request by Abdelaziz18003**

### CODE REVIEW

**Comment by mahnouman** [comment]
Hello, please separate the demo data itself outside the .vue template, for example if I want to change the demo post, editing inside a .vue template for this purpose does not look neat.

**Comment by Abdelaziz18003** [comment]
I thought about that. But, I saw that demo data are not going to be changed a lot so it maybe Ok to keep it inside the "hello-world-injector". if the database page grows we will separate this injector to its component. the advantage it that we will have the whole feature in the one single file that don't depend on any other file. Just think about it that way and tell me again if it still needs extraction and I will do it

**Comment by Abdelaziz18003** [comment]
Ok clear for the data, I will extract it to its own file. for the simple post it doesn't contain images it just a title, simple text body, author and some tags .. should we add images for it ?

**Comment by mahnouman** [comment]
Hello. Yes. This sample data should be a good representation of the platform. Is there a way to make a local image uploaded?

**Comment by Abdelaziz18003** [comment]
We can make a local image uploaded by reading it from the hard disk and upload it .. But, as I know it you need it's absolute path for that (ex: C:\tamiat\tamiatlogo.png) and we are not aware where the user puts his project folder .. as I am doing now for the logo is downloading it from the github repo and then upload it .. by the way post image you mean featured image or post body image or the two ?

**Comment by mahnouman** [comment]
Hello. Both

**Comment by Abdelaziz18003** [comment]
@mahnouman normally everything is Ok now

**Comment by mahnouman** [comment]
Hello Abdelaziz, Thanks I will merge then test :)

**Pull request merged**
